/* Generated By:JavaCC: Do not edit this line. JavaCCConstants.java */
package JavaCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int MULTIPLY = 6;
  /** RegularExpression Id. */
  int DIVIDE = 7;
  /** RegularExpression Id. */
  int BLOCK_IN = 8;
  /** RegularExpression Id. */
  int BlOCK_OUT = 9;
  /** RegularExpression Id. */
  int INTEGER = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int DOUBLE = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int FOR = 15;
  /** RegularExpression Id. */
  int VAR = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int CONSTANT = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int STR = 24;
  /** RegularExpression Id. */
  int LINE_COMMENT = 25;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;
  /** Lexical state. */
  int IN_BLOCK_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\"INT\"",
    "\"STRING\"",
    "\"DOUBLE\"",
    "\"IF\"",
    "\"ELSE\"",
    "\"FOR\"",
    "\"VAR\"",
    "<IDENTIFIER>",
    "<CONSTANT>",
    "<DIGIT>",
    "\"\\\"\"",
    "<token of kind 21>",
    "<token of kind 22>",
    "<token of kind 23>",
    "\"\\\"\"",
    "<LINE_COMMENT>",
    "\"/*\"",
    "<token of kind 27>",
    "<token of kind 28>",
    "\"\\n\"",
    "\"f:\"",
    "\"r:\"",
    "\"m-:\"",
    "\"m+:\"",
    "\":\"",
    "\"%\"",
  };

}
